server:
  port: 8080
spring:
  application:
    name: finance
  graphql:
    graphiql:
      enabled: true
    schema:
      locations: classpath:graphql/**/
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
